PlataApp/Models/Plata.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Plata
    {
        public int Id { get; set; }

        [Display(Name = "Ime")]
        [DataType(DataType.Text, ErrorMessage = "Unesite validno ime")]
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string Ime { get; set; }

        [Display(Name = "Prezime")]
        [DataType(DataType.Text, ErrorMessage = "Unesite validno prezime")]
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string Prezime { get; set; }

        [Display(Name = "Adresa")]
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string Adresa { get; set; }

        [Display(Name = "Iznos Neto Plate")]
        [Required]
        [Range(29429.00, 1000000, ErrorMessage = "Neto plata ne moze biti manja od minimalne zarade ili veca od 1000000.")]
        public decimal NetoPlata { get; set; }

        [Display(Name = "BRUTO 1")]
        [ReadOnly(true)]
        public decimal Bruto1 { get; set; }

        [Display(Name = "Iznos Poreskog Oslobodjenja")]
        [ReadOnly(true)]

        public decimal PoreskoOslobodjenje { get; set; }

        [Display(Name = "Poreska Osnovica")]
        [ReadOnly(true)]
        public decimal PoreskaOsnovica { get; set; }

        [Display(Name = "Iznos Poreske Stope")]
        [ReadOnly(true)]
        public decimal PoreskaStopa { get; set; }

        [Display(Name = "PIO na teret zaposlenog")]
        [ReadOnly(true)]
        public decimal PioZap { get; set; }

        [Display(Name = "Zdravstveno osiguranje na teret zaposlenog")]
        [ReadOnly(true)]
        public decimal ZdrOsigZap { get; set; }

        [Display(Name = "Nezaposlenost")]
        [ReadOnly(true)]
        public decimal Nezaposlenost { get; set; }

        [Display(Name = "PIO na teret poslodavca")]
        [ReadOnly(true)]
        public decimal PioPoslodavac { get; set; }

        [Display(Name = "Zdravstveno osiguranje na teret poslodavca")]
        [ReadOnly(true)]
        public decimal ZdrOsigPoslodavac { get; set; }

        [Display(Name = "BRUTO 2")]
        [ReadOnly(true)]
        public decimal Bruto2 { get; set; }
    }
}

PlataApp/Models/PlataModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlataZadatakDBEntities : DbContext
    {
        public PlataZadatakDBEntities()
            : base("name=PlataZadatakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Plata> Platas { get; set; }
    }
}

PlataApp/Models/PlataModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\prlji\source\repos\PlataApp\PlataApp\Models\PlataModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

PlataApp/Models/PlataModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

PlataApp/Controllers/PlatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlataApp.Models;

namespace PlataApp.Controllers
{
    public class PlatasController : Controller
    {
        private PlataZadatakDBEntities db = new PlataZadatakDBEntities();

        // GET: Platas
        public ActionResult Index()
        {
            return View(db.Platas.ToList());
        }

       
          // GET: Platas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Platas/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ime,Prezime,Adresa,NetoPlata,Bruto1,PoreskoOslobodjenje,PoreskaOsnovica,PoreskaStopa,PioZap,ZdrOsigZap,Nezaposlenost,PioPoslodavac,ZdrOsigPoslodavac,Bruto2")] Plata plata)
        {
            if (ModelState.IsValid)
            {
                plata.Bruto1 = (plata.NetoPlata - 1830) / 701 * 1000;
                plata.PoreskoOslobodjenje = 18300;
                plata.PoreskaOsnovica = plata.Bruto1 - 18300;
                if (plata.PoreskaOsnovica >= 405750)
                {
                    plata.PoreskaOsnovica = 405750;
                }

                plata.PoreskaStopa = plata.PoreskaOsnovica / 100 * 10;
                plata.PioZap = plata.Bruto1 / 100 * 14;
                plata.ZdrOsigZap = plata.Bruto1 / 10000 * 515;
                plata.Nezaposlenost = plata.Bruto1 / 10000 * 75;
                plata.ZdrOsigPoslodavac = plata.Bruto1 / 1000 * 115;
                plata.PioPoslodavac = plata.Bruto1 / 10000 * 515;
                plata.Bruto2 = plata.Bruto1 + plata.ZdrOsigPoslodavac + plata.PioPoslodavac;

                db.Platas.Add(plata);
                db.SaveChanges();
            }

            return View(plata);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PlataApp/Views/Platas/Create.cshtml
@model PlataApp.Models.Plata


@{
    ViewBag.Title = "Obracun";
}
<html>
<head>
   

    <style>
        .names {
            display: flex;
            align-content: center;
        }

        .result {
            display: flex;
            align-self: center;
            font-size: 16px;
            font-weight: bold;
            margin-left: 3vw;
            border-bottom: 2px solid indianred;
        }

        .form-horizontal .dialog .control-label {
            display: flex;
            align-content: center;
            font-size: 16px;
            padding-top: 0;
        }

        .dialog {
            margin-top: 15vh;
            display: flex;
            align-content: center;
            justify-content: space-between;
        }

        .dialog-right {
            display: flex;
            align-self: center;
            flex-direction: column-reverse;
        }

        .okvir {
        }

        .form-group .btn {
            margin-top: 3vh;
        }

        @@media (max-width: 1200px) {
            .dialog {
                padding-left: 20px;
                flex-direction: column;
                justify-content: flex-start;
            }

            .dialog-right {
                align-self: flex-start;
                flex-direction: column;
            }
        }
    </style>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <br />
        <br />
        <br />
        <h4>Obracun plate</h4>
        <hr />
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <form id="my-form">
                <div class="form-group">
                    @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NetoPlata, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NetoPlata, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NetoPlata, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Izracunaj" class="btn btn-danger" />
                    </div>
                </div>

            </form>

            <!--OBRACUN-->

            <div class="dialog">
                <div class="dialog-left">
                    <div class="form-group names">
                        @Html.LabelFor(model => model.Bruto1, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.Bruto1)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.PoreskoOslobodjenje, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.PoreskoOslobodjenje)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.PoreskaOsnovica, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.PoreskaOsnovica)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.PoreskaStopa, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.PoreskaStopa)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.PioZap, htmlAttributes: new { @class = "control-label " })
                        <div class="result">
                            @Html.DisplayFor(model => model.PioZap)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.ZdrOsigZap, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.ZdrOsigZap)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.Nezaposlenost, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.Nezaposlenost)
                        </div>
                    </div>
                </div>
                <div class="dialog-right">
                    <div class="form-group names">
                        @Html.LabelFor(model => model.PioPoslodavac, htmlAttributes: new { @class = "control-label " })
                        <div class="result">
                            @Html.DisplayFor(model => model.PioPoslodavac)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.ZdrOsigPoslodavac, htmlAttributes: new { @class = "control-label" })
                        <div class="result">
                            @Html.DisplayFor(model => model.ZdrOsigPoslodavac)
                        </div>
                    </div>
                    <div class="form-group names">
                        @Html.LabelFor(model => model.Bruto2, htmlAttributes: new { @class = "control-label " })
                        <div class="result">
                            @Html.DisplayFor(model => model.Bruto2)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
}

PlataApp/Views/Platas/Index.cshtml
@model IEnumerable<PlataApp.Models.Plata>

@{
    ViewBag.Title = "Lista Podataka";
}

<h2>Lista</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NetoPlata)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bruto1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PoreskoOslobodjenje)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PoreskaOsnovica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PoreskaStopa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PioZap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZdrOsigZap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nezaposlenost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PioPoslodavac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZdrOsigPoslodavac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bruto2)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NetoPlata)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bruto1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PoreskoOslobodjenje)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PoreskaOsnovica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PoreskaStopa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PioZap)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZdrOsigZap)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nezaposlenost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PioPoslodavac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZdrOsigPoslodavac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bruto2)
        </td>
       
    </tr>
}

</table>

PlataApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Zadatak</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Zadatak", "Create", "Platas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse " style="float: right">
                <ul class="nav navbar-nav ml-auto">
                    <li>@Html.ActionLink("Obracun", "Create", "Platas")</li>
                    <li>@Html.ActionLink("Lista", "Index", "Platas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>